#!/bin/bash

if [ -z "$1" ]; then
    echo "Usage: create_jtp_image KG805_CERT_radio.img"
    exit 1
fi

if ! [ -f "$1" ]; then
    echo "File not found"
    exit 1
fi

filename="${1}"
filename_no_ext="${filename%.*}"
jtp_image="${filename_no_ext} plus JTP.img"
cp "${filename}" "${jtp_image}"

# Channel 5, CTCSS 131.8
chirpc -r Wouxun_KG-805G --mmap "${jtp_image}" --set-mem-freq 462662500 --set-mem-tsqlon --set-mem-tsql 131.8 --set-mem-mode FM --set-mem-name JTBUS 109

# Channel 16, CTCSS 71.9
chirpc -r Wouxun_KG-805G --mmap "${jtp_image}" --set-mem-freq 462575000 --set-mem-tsqlon --set-mem-tsql 71.9 --set-mem-mode FM --set-mem-name JTP1HP 110

# Channel 3, CTCSS 71.9
chirpc -r Wouxun_KG-805G --mmap "${jtp_image}" --set-mem-freq 462612500 --set-mem-tsqlon --set-mem-tsql 71.9 --set-mem-mode FM --set-mem-name JTP2LP 111
