"ABANDONED VEHICLE" = "Service Call"
"ALARM" = "Service Call"
"ALARM, AUDIBLE" = "Service Call"
"ALARM, SILENT" = "Service Call"
"ALARM, SVRN" = "Service Call"
"ALTERED VIN NUMBER" = "Fraud"
"ANIMAL COMPLAINT" = "Other"
"ARMED ROBBERY" = "Robbery"
"ARMED ROBBERY (COMBINED EVENT)" = "Robbery"
"ARSON (447A)" = "Vandalism"
"ASSAULT" = "Assault"
"ASSAULT AND BATTERY" = "Assault"
"ASSAULT ON AN OFFICER" = "Assault"
"ASSAULT WITH DEADLY WEAPON" = "Assault"
"ASSAULT WITH DEADLY WEAPON (COMBINED EVENT)" = "Assault"
"ASSAULT WITH DEADLY WEAPON, GANG" = "Assault"
"BAD CHECKS" = "Fraud"
"BAR CHECK" = "Service Call"
"BATTERY" = "Assault"
"BATTERY (COMBINED EVENT)" = "Assault"
"BATTERY, GANG RELATED" = "Assault"
"BATTERY ON AN OFFICER" = "Assault"
"BATTERY ON A PEACE OFFICER" = "Assault"
"BATTERY, SERIOUS INJURY" = "Assault"
"BOMB THREAT" = "Other"
"BRANDISHING A WEAPON" = "Weapons"
"BRANDISHING A WEAPON, GANG" = "Weapons"
"BREACH OF AOA" = "Service Call"
"BURGLARY (460)" = "Burglary"
"BURGLARY  REPORT  (460)" = "Burglary"
"CALL_TYPE" = "Other"
"CARJACKING (COMBINED EVENT)" = "Vehicle Break-in/Theft"
"CARRYING A CONCEALED WEAPON" = "Weapons"
"CHILD ABUSE" = "Assault"
"CHILD BEATING" = "Assault"
"CIVIL MATTER" = "Other"
"COMMUNIT POLICING BIKE" = "Non-criminal"
"COMMUNITY POLICING -CITZ ASSIST" = "Non-criminal"
"COMMUNITY POLICING MEETING" = "Non-criminal"
"COMMUNITY POLICING OFFICE" = "Non-criminal"
"COMMUNITY POLICING SCHOOL" = "Non-criminal"
"CONTROLLED SUBSTANCE AT RESIDENCE" = "Drugs/Alcohol"
"CORONERS CASE" = "Other"
"CRIMINAL THREATS" = "Assault"
"CRUELTY TO ANIMALS" = "Other"
"DEAD ANIMAL" = "Service Call"
"DEFRAUDING AN INKEEPER" = "Fraud"
"DISTURBANCE" = "Disturbing Peace"
"DISTURBANCE (COMBINED EVENT)" = "Disturbing Peace"
"DISTURBANCE, FAMILY" = "Disturbing Peace"
"DISTURBANCE, FAMILY (COMBINED EVENT)" = "Disturbing Peace"
"DISTURBANCE, FIGHT" = "Disturbing Peace"
"DISTURBANCE, FIGHT (COMBINED EVENT)" = "Disturbing Peace"
"DISTURBANCE, FIRECRACKERS" = "Disturbing Peace"
"DISTURBANCE, GANG" = "Disturbing Peace"
"DISTURBANCE, JUVENILE" = "Disturbing Peace"
"DISTURBANCE, MOTORCYCLE" = "Disturbing Peace"
"DISTURBANCE, MUSIC" = "Disturbing Peace"
"DISTURBANCE, NEIGHBOR" = "Disturbing Peace"
"DISTURBANCE, UNKNOWN" = "Disturbing Peace"
"DISTURBANCE, UNKNOWN (COMBINED EVENT)" = "Disturbing Peace"
"DISTURBANCE, WEAPON" = "Disturbing Peace"
"DISTURBANCE, WEAPON (COMBINED EVENT)" = "Disturbing Peace"
"DOMESTIC VIOLENCE  (COMBINED EVENT)" = "Assault"
"DRIVING W/SUSPENDED LICENSE" = "Traffic"
"DRUNK IN PUBLIC" = "Drugs/Alcohol"
"ELDER/DEPENDENT ADULT ABUSE" = "Assault"
"EMBEZZLEMENT" = "Larceny"
"EXPIRED REGISTRATION" = "Traffic"
"EXPLOSION" = "Other"
"EXTORTION" = "Robbery"
"FALSE IMPRISONMENT" = "Other"
"FELONY DUI" = "DUI"
"FELONY HIT AND RUN" = "Traffic"
"FELONY WANT" = "Other"
"FEMALE CALLING FOR HELP" = "Other"
"FIREARMS DISCHARGED" = "Weapons"
"FIRE DEPARTMENT REQUEST FOR PD" = "Other"
"FIRE (SPECIFY TYPE)" = "Other"
"FORGERY" = "Fraud"
"FOUND, MISSING PERSON" = "Missing Person"
"FOUND PROPERTY" = "Service Call"
"GARBAGE COMPLAINT" = "Service Call"
"GRAND THEFT" = "Larceny"
"HANDICAPPED PARKING VIOLATION" = "Service Call"
"HATE CRIMES" = "Other"
"HI-TECH CRIMES" = "Other"
"ILLEGAL WEAPONS" = "Weapons"
"ILLEGAL WEAPONS, GANG RELATED" = "Weapons"
"INDECENT EXPOSURE" = "Sex Crime"
"INJURED ANIMAL" = "Other"
"INJURED PERSON" = "Other"
"INTOXICATED PERSON" = "Drugs/Alcohol"
"KIDNAPPING" = "Other"
"MALICIOUS MISCHIEF" = "Vandalism"
"MALICIOUS MISCHIEF, GANG RELATED" = "Vandalism"
"MEET THE CITIZEN" = "Non-criminal"
"MENTALLY DISTURBED FEMALE" = "Disturbing Peace"
"MENTALLY DISTURBED PERSON" = "Disturbing Peace"
"MISDEMEANOR DUI" = "DUI"
"MISDEMEANOR HIT AND RUN" = "Traffic"
"MISDEMEANOR WANT" = "Other"
"MISSING FEMALE" = "Missing Person"
"MISSING FEMALE JUVENILE" = "Missing Person"
"MISSING JUVENILE" = "Missing Person"
"MISSING PERSON" = "Missing Person"
"MISSING PERSON, MENTAL HANDICAP" = "Missing Person"
"MOLEST/ANNOY UNDER 18YRS" = "Sex Crime"
"MURDER" = "Assault"
"NARCOTICS" = "Drugs/Alcohol"
"NARCOTICS, GANG RELATED" = "Drugs/Alcohol"
"OBSCENE OR HARASSING PH CALLS" = "Assault"
"OBSTRUCT STREETS OR SIDEWALK" = "Service Call"
"OPEN DOOR" = "Service Call"
"OPEN WINDOW" = "Service Call"
"PARKING VIOLATION" = "Traffic"
"PAROLE VIOLATION" = "Other"
"PEDESTRIAN STOP" = "Other"
"PEDESTRIAN STOP ON FEMALE" = "Other"
"PERSON CALLING FOR HELP" = "Public Safety"
"PERSON SHOT" = "Assault"
"PERSON STABBED" = "Assault"
"PETTY THEFT" = "Larceny"
"PETTY THEFT (BROADCAST ONLY)" = "Larceny"
"PETTY THEFT PRIOR CONVICTION" = "Larceny"
"POSSESSION OF CONTROLLED SUBSTANCE" = "Drugs/Alcohol"
"POSSESSION OF CONTROLLED SUBSTANCE, GANG RELATED" = "Drugs/Alcohol"
"POSSESSION OF MARIJUANA" = "Drugs/Alcohol"
"POSSESSION OF NARCOTICS" = "Drugs/Alcohol"
"POSSESSION OF NARCOTICS, GANG RELATED" = "Drugs/Alcohol"
"PROWLER" = "Suspicious Person"
"PUBLIC SAFETY ASSISTANCE" = "Public Safety"
"PURSE SNATCH ROBBERY" = "Robbery"
"RECEIVE/POSSESS STOLEN PROP" = "Larceny"
"RECKLESS DRIVING" = "Traffic"
"RECOVERED STOLEN VEHICLE" = "Vehicle Break-in/Theft"
"REFUSAL TO LEAVE PROPERTY" = "Trespassing"
"REGISTRATION OF SEX OFFENDER" = "Sex Crime"
"RESISTING ARREST" = "Assault"
"RESISTING ARREST, GANG RELATED" = "Assault"
"ROBBERY" = "Robbery"
"ROBBERY, GANG RELATED" = "Robbery"
"SHOOTING INTO OCCP VEH OR DWELLING" = "Assault"
"SICK PERSON" = "Public Safety"
"SOLICITING FOR LEWD CONDUCT" = "Sex Crime"
"SOLICITING FOR PROSTITUTION" = "Sex Crime"
"SPEED CONTEST" = "Traffic"
"SPEEDING" = "Traffic"
"STALKING" = "Public Safety"
"STOLEN VEHICLE" = "Vehicle Break-in/Theft"
"STOLEN VEHICLE, GANG RELATED" = "Vehicle Break-in/Theft"
"STRONG ARM ROBBERY" = "Robbery"
"STRONG ARM ROBBERY (COMBINED EVENT)" = "Robbery"
"SUSPICIOUS CIRCUMSTANCES" = "Suspicious Person"
"SUSPICIOUS CIRCUMSTANCES (COMBINED EVENT)" = "Suspicious Person"
"SUSPICIOUS FEMALE" = "Suspicious Person"
"SUSPICIOUS PACKAGE" = "Suspicious Person"
"SUSPICIOUS PERSON" = "Suspicious Person"
"SUSPICIOUS PERSON (GANG)" = "Suspicious Person"
"SUSPICIOUS PERSON ON RUNWAY - SJIA" = "Suspicious Person"
"SUSPICIOUS PERSON W/ WEAPON" = "Suspicious Person"
"SUSPICIOUS VEHICLE" = "Suspicious Person"
"TAKE A REPORT" = "Service Call"
"TAMPERING WITH A VEHICLE" = "Vandalism"
"THEFT" = "Larceny"
"THEFT, GANG RELATED" = "Larceny"
"THEFT OF RECYCLABLES" = "Larceny"
"THROWING SUBSTANCES AT VEHICLE" = "Vandalism"
"TRAFFIC CONTROL" = "Traffic"
"TRAFFIC HAZARD" = "Traffic"
"TRESPASSING" = "Trespassing"
"UNK TYPE 911 CALL" = "Other"
"UNLICENSED DRIVER" = "Traffic"
"USE OF CONTROLLED SUBSTANCE" = "Drugs/Alcohol"
"VAGRANT" = "Suspicious Person"
"VEHICLE ACCIDENT, AMB DISPATCHED" = "Vehicle Accident"
"VEHICLE ACCIDENT, MAJOR INJURIES" = "Vehicle Accident"
"VEHICLE ACCIDENT, MINOR INJURIES" = "Vehicle Accident"
"VEHICLE ACCIDENT, PROPERTY DAMAGE" = "Vehicle Accident"
"VEHICLE ACCIDENT, UNKNOWN INJURIES" = "Vehicle Accident"
"VEHICLE BURGLARY" = "Vehicle Break-in/Theft"
"VEHICLE STOP" = "Traffic"
"VEHICLE STOP ON FEMALE" = "Traffic"
"VEHICLE STOP, SEND FILL" = "Traffic"
"VICIOUS ANIMAL" = "Other"
"VIOLATION OF PROTECTIVE ORDER" = "Other"
"WELFARE CHECK" = "Welfare Check"
"WELFARE CHECK (COMBINED EVENT)" = "Welfare Check"
"W&I-UNDER JURIS OF JUV COURT" = "Other"
